### PR TITLE
popoup didn't occured issue fixed

### PR DESCRIPTION
**Pull request by Rajibshrestha59**
https://growthlab.atlassian.net/browse/NFTRWP-102?atlOrigin=eyJpIjoiOGU1YjAzZTdjMGFkNDA2OWE1ZDcwMTQ5ODNmOWNhNzciLCJwIjoiaiJ9

### CODE REVIEW

**Review by biswanathsahoo — CHANGES_REQUESTED** [review]
The signup and import contact flow is still not working. Please check once

**Comment by Rajibshrestha59** [comment]
> The signup and import contact flow is still not working. Please check once

Please check once

**Comment by biswanathsahoo** [comment]
Please resolve the conflict

**Comment by sparkyrider** [comment]
@Rajibshrestha59 any updates on this? This is pending merge

**Pull request closed without merging**
