### PR TITLE
issue fixed

### PR DESCRIPTION
**Pull request by Rajibshrestha59**

### CODE REVIEW

**Comment by biswanathsahoo** [comment]
Still it's not showing the imported contact in the contact list popup 

contact-list-popup

**Comment by biswanathsahoo** [comment]
Also, on closing the contact list popup, it's not opening the create NFT popup

**Comment by Rajibshrestha59** [comment]
> Still it's not showing the imported contact in the contact list popup
> 
> contact-list-popup

@biswanathsahoo  are you getting any error message while importing?

**Comment by biswanathsahoo** [comment]
> > Still it's not showing the imported contact in the contact list popup
> > contact-list-popup
> 
> @biswanathsahoo are you getting any error message while importing?

No, it's imported successfully

**Pull request closed without merging**
